CREATE OR REPLACE  VIEW UTIL.SYS_LOG_TODAY AS 
SELECT SL.ID,
       SL.APPL_PROC,
       SL.MESSAGE,
       SL.STATUS,
       SL.LOG_DATE
FROM UTIL.SYS_LOG SL
WHERE SL.LOG_DATE >= TRUNC(SYSDATE,'dd');   


  
