GRANT EXECUTE ON SYS.GET_CURR_NBU TO UTIL;
GRANT EXECUTE ON SYS.READ_FILE TO UTIL;
GRANT CREATE TABLE TO UTIL;
GRANT CREATE VIEW TO UTIL;
GRANT CREATE PROCEDURE TO UTIL;
GRANT DEBUG CONNECT SESSION TO UTIL;
GRANT CREATE JOB TO UTIL;
