CREATE TABLE UTIL.CUR_EXCH_RATE
(
ID NUMBER NOT NULL ENABLE,
CURR_ID NUMBER NOT NULL ENABLE,
CURR_TEXT VARCHAR2(20) NOT NULL ENABLE,
RATE NUMBER NOT NULL ENABLE,
CURR_CODE VARCHAR2(3) NOT NULL ENABLE,
CURR_TYPE VARCHAR2(10),
CHECK (STATUS IN ('MONEY','CRYPTO','PRE_METAL')),
EXCHANGEDATE DATE DEFAULT TRUNC(SYSDATE,'DD'),
JSON_VALUE VARCHAR2(500),
CHECK (JSON_VALUE IS JSON)
)
;
