CREATE TABLE UTIL.CUR_EXCH_RATE
(
ID NUMBER NOT NULL ENABLE,
CURR_ID NUMBER,
CURR_TEXT VARCHAR2(50),
RATE NUMBER,
CURR_CODE VARCHAR2(4),
CURR_TYPE VARCHAR2(10), CHECK (CURR_TYPE IN ('MONEY','CRYPTO','PRE_METAL')),
EXCHANGEDATE DATE DEFAULT TRUNC(SYSDATE,'DD'),
JSON_VALUE VARCHAR2(500),
CHECK (JSON_VALUE IS JSON)
)
;

COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."ID" IS 'Унікальний номер.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."CURR_ID" IS 'Ідентифікатор валюти.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."CURR_TEXT" IS 'Назва валюти.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."RATE" IS 'Відсоток.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."CURR_CODE" IS 'Код курсу валют.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."CURR_TYPE" IS 'Тип курсу валют.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."EXCHANGEDATE" IS 'Дата оновлення інформації про валюту.';
COMMENT ON COLUMN "UTIL"."CUR_EXCH_RATE"."JSON_VALUE" IS 'Значання в форматі JSON.';
