CREATE TABLE UTIL.CUR_EXCH_RATE_HISTORY
(
ID NUMBER NOT NULL ENABLE,
CURR_ID NUMBER NOT NULL ENABLE,
CURR_TEXT VARCHAR2(20) NOT NULL ENABLE,
RATE NUMBER NOT NULL ENABLE,
CURR_CODE VARCHAR2(3) NOT NULL ENABLE,
CURR_TYPE VARCHAR2(10) CHECK (CURR_TYPE IN ('MONEY','CRYPTO','PRE_METAL')),
EXCHANGEDATE DATE DEFAULT TRUNC(SYSDATE,'dd'),
CHANGE_USER VARCHAR2(100) DEFAULT USER,
CHANGE_DATE DATE DEFAULT SYSDATE
);
