CREATE OR REPLACE NONEDITIONABLE FUNCTION SYS.READ_FILE(P_LOCATION IN VARCHAR2,
                                                        P_FILENAME IN VARCHAR2)
  RETURN VARCHAR2 IS

  V_FILE     SYS.UTL_FILE.FILE_TYPE;
  V_LOCATION VARCHAR2(100) := P_LOCATION;
  V_FILENAME VARCHAR2(100) := P_FILENAME;
  V_TEXT     VARCHAR2(32767);
  V_JSON     VARCHAR2(32767);

BEGIN

  BEGIN
    V_FILE := UTL_FILE.FOPEN(V_LOCATION, V_FILENAME, 'r');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  BEGIN
    LOOP
      UTL_FILE.GET_LINE(V_FILE, V_TEXT);
      V_JSON := V_JSON || V_TEXT;
    END LOOP;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  UTL_FILE.FCLOSE(V_FILE);

  RETURN V_JSON;

END;
/
