--SET SERVEROUTPUT ON
DECLARE
  F    UTL_FILE.FILE_TYPE;
  LINE VARCHAR2(255);
  S    TIMESTAMP;
BEGIN
  F := UTL_FILE.FOPEN('DIR_FILES', 'C:\odb19\DIR_FILES\temp.txt', 'w');
  S := SYSTIMESTAMP;
  FOR I in (SELECT * FROM hr.jobs) LOOP
   LINE := I.JOB_ID || ';' || I.JOB_TITLE || ';' || I.MIN_SALARY || ';' || I.MAX_SALARY;
    UTL_FILE.PUT_LINE(F, LINE);
  END LOOP;
  --DBMS_OUTPUT.PUT_LINE(SYSTIMESTAMP - S);
  UTL_FILE.FCLOSE_ALL;
END;
/

------------------------------------
--SET SERVEROUTPUT ON
DECLARE
  L_FILE     UTL_FILE.FILE_TYPE;
  L_LOCATION VARCHAR2(100) := 'DIR_FILES';
  L_FILENAME VARCHAR2(100) := 'C:\odb19\DIR_FILES\temp.txt';
  L_TEXT     VARCHAR2(32767);
BEGIN
  L_FILE := UTL_FILE.FOPEN(L_LOCATION, L_FILENAME, 'r');

  BEGIN
    LOOP
      UTL_FILE.GET_LINE(L_FILE, L_TEXT);
      DBMS_OUTPUT.PUT_LINE(L_TEXT);
    END LOOP;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      NULL;
  END;
  UTL_FILE.FCLOSE(L_FILE);
END;
/
