INSERT INTO UTIL.CURR_TYPE(ID, CURR_CODE, CURR_TYPE)
SELECT 1, 'USD', 'MONEY' FROM DUAL UNION
SELECT 2, 'EUR', 'MONEY' FROM DUAL UNION
SELECT 3, 'GBP', 'MONEY' FROM DUAL UNION
SELECT 4, 'PLN', 'MONEY' FROM DUAL UNION
SELECT 5, 'XAU', 'PRE_METAL' FROM DUAL UNION
SELECT 6, 'XAG', 'PRE_METAL' FROM DUAL UNION
SELECT 7, 'USDT', 'CRYPTO' FROM DUAL UNION
SELECT 8, 'BUSD', 'CRYPTO' FROM DUAL;

COMMIT;
